### PR TITLE
Bump Clang_jll's version

### LINKED ISSUE #464: Unable to install Clang.jl on Julia master for 1.11-dev - needs new libLLVM_jll
```
(@v1.11) pkg> add Clang@0.17.8
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package libLLVM_jll [8f36deef]:
 libLLVM_jll [8f36deef] log:
 ├─possible versions are: 16.0.6 or uninstalled
 └─found to have no compatible versions left with Clang_jll [0ee61d77]
   └─Clang_jll [0ee61d77] log:
     ├─possible versions are: 9.0.1 - 17.0.6 or uninstalled
     └─restricted by compatibility requirements with Clang [40e3b903] to versions: 12.0.0 - 15.0.7
       └─Clang [40e3b903] log:
         ├─possible versions are: 0.7.0 - 0.17.8 or uninstalled
         └─restricted to versions 0.17.8 by an explicit requirement, leaving only versions: 0.17.8```

### PR DESCRIPTION
**Pull request by Gnimuc**
fix #464

### CODE REVIEW

**Comment by Gnimuc** [comment]
# Clang 16:
```
getTypeDeclaration(type) = CLCursor (Clang.CLStructDecl) ImDrawChannel
 Clang.CLStructDecl ImDrawChannel
    Clang.CLFieldDecl a Clang.CLElaborated ImVector_ImDrawCmd _CmdBuffer
    Clang.CLFieldDecl a Clang.CLElaborated ImVector_ImDrawIdx _IdxBuffer
(c, ty, getNamedType(ty)) = (CLCursor (Clang.CLFieldDecl) _CmdBuffer, CLType (Clang.CLElaborated) , CLType (Clang.CLTypedef) )
ERROR: LoadError: AssertionError: jlty isa JuliaCenum || jlty isa JuliaCrecord
Stacktrace:
 [1] tojulia(x::Clang.CLElaborated)
   @ Clang.Generators ~/.julia/dev/Clang/src/generator/jltypes.jl:151
 [2] collect_dependent_system_nodes!(dag::ExprDAG, type::Clang.CLRecord, system_nodes::Dict{ExprNode, Int64})
   @ Clang.Generators ~/.julia/dev/Clang/src/generator/system_deps.jl:133
 [3] collect_dependent_system_nodes!(dag::ExprDAG, node::ExprNode{Clang.Generators.StructForwardDecl, Clang.CLStructDecl}, system_nodes::Dict{ExprNode, Int64})
   @ Clang.Generators ~/.julia/dev/Clang/src/generator/system_deps.jl:124
```

#### Clang 15
```
getTypeDeclaration(type) = CLCursor (Clang.CLStructDecl) ImDrawChannel
 Clang.CLStructDecl ImDrawChannel
    Clang.CLFieldDecl a Clang.CLTypedef ImVector_ImDrawCmd _CmdBuffer
    Clang.CLFieldDecl a Clang.CLTypedef ImVector_ImDrawIdx _IdxBuffer
ERROR: LoadError: MethodError: no method matching getNamedType(::Clang.CLTypedef)

Closest candidates are:
  getNamedType(::Clang.CLElaborated)
   @ Clang ~/.julia/dev/Clang/src/type.jl:152
  getNamedType(::Clang.LibClang.CXType)
   @ Clang ~/.julia/dev/Clang/src/type.jl:151

Stacktrace:
 [1] macro expansion
   @ ./show.jl:1181 [inlined]
 [2] collect_dependent_system_nodes!(dag::ExprDAG, type::Clang.CLRecord, system_nodes::Dict{ExprNode, Int64})
   @ Clang.Generators ~/.julia/dev/Clang/src/generator/system_deps.jl:132
```

**Comment by Gnimuc** [comment]
I dont know why `ImVector_ImDrawCmd` needs to be represented as an `elaborated` type.

**Comment by JamesWrigley** [comment]
MWE:
```c
typedef int foo;

typedef struct X
{
    foo field;
} X;
```

Also, where is `CLElaborated` defined? :thinking: It's used in a couple places but I can't find the definition anywhere.

**Comment by JamesWrigley** [comment]
Oh NVM, I see it's created automatically in `cltypes.jl`. Man, this is weird :confused: I might try doing a poor-mans bisect with the available `Clang_jll` versions: https://github.com/JuliaRegistries/General/blob/master/jll/C/Clang_jll/Versions.toml

**Comment by Gnimuc** [comment]
> Oh NVM, I see it's created automatically in `cltypes.jl`. Man, this is weird 😕 I might try doing a poor-mans bisect with the available `Clang_jll` versions: https://github.com/JuliaRegistries/General/blob/master/jll/C/Clang_jll/Versions.toml

it would be faster to check the source directly. but this is not urgent. one can always run the generator with the old Julia version .

**Comment by JamesWrigley** [comment]
Actually I need it to fix more method ambiguities in 1.11 :sweat_smile: Example failure: https://github.com/JuliaWeb/LibSSH.jl/actions/runs/7698581250/job/20978180881

Similar to #458. But you're right, it's not urgent yet.

**Pull request merged**
