### PR TITLE
(Possible) workaround for structs/unions that have unexposed FirstAttr fields

### PR DESCRIPTION
**Pull request by wsphillips**
Attempt at fix for issue #249

### CODE REVIEW

**Comment by Gnimuc** [comment]
This makes me feel again that libclang is not an appropriate tool for building a wrapper generator. It looks like the major audience of libclang is IDE-tools-writer, that's why it doesn't expose enough APIs we needed and hence some subroutines of the `wrap!()` function look too hairy. 

I think one day we should rewrite the package to be a true wrapper over Clang's C++ API instead of libclang's C API. Cxx.jl is a very promising tool for this job, but it lacks good maintenance for now. I would expect this to be done in the Julia-v1.4~v1.5 period. But before that, I guess it's good to go with libclang + hairy code.

**Comment by Gnimuc** [comment]
Better to add some tests in this PR. :)

**Comment by wsphillips** [comment]
> This makes me feel again that libclang is not an appropriate tool for building a wrapper generator. It looks like the major audience of libclang is IDE-tools-writer, that's why it doesn't expose enough APIs we needed and hence some subroutines of the `wrap!()` function look too hairy.

Yeah, I've just adopted existing `wrap!()` routines as a starting point/template in most cases. To be fair, it's partly to do with sometimes poorly written C APIs!

I will be sure to come back and add tests in a couple days once I have this current mess out of the way.

**Comment by Gnimuc** [comment]
I'm going to merge this, tests can be added in another PR in the future. Thanks for contribution!

**Pull request merged**
