### PR TITLE
Modules support (finish #425)

### PR DESCRIPTION
**Pull request by christiangnrd**
This PR attempts to finish #425 which was seemingly abandoned with only docstrings missing. I cherry-picked the commit from #425 that wasn't already merged, and added the missing docstrings.

Closes #425

### CODE REVIEW

**Comment by JamesWrigley** [comment]
Yeah I ran into that yesterday: https://github.com/JuliaInterop/Clang.jl/pull/502#issuecomment-2299223118
I'll cherry-pick the fix and make a PR.

**Comment by Gnimuc** [comment]
rebased on the latest master

**Comment by Gnimuc** [comment]
I think this is ready to be merged?

**Comment by christiangnrd** [comment]
I think so!

**Pull request merged**
