### PR TITLE
Allow -x c++ to work

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
Attempt at fixing https://github.com/JuliaInterop/Clang.jl/issues/430#issuecomment-1548781755

**Comment by vchuravy** [comment]
Struggles still with:

```
/// Severity of a diagnostic.
enum MlirDiagnosticSeverity {
  MlirDiagnosticError,
  MlirDiagnosticWarning,
  MlirDiagnosticNote,
  MlirDiagnosticRemark
};
typedef enum MlirDiagnosticSeverity MlirDiagnosticSeverity;
```

**Comment by vchuravy** [comment]
Motivating PR in MLIR.jl https://github.com/JuliaLabs/MLIR.jl/pull/10, but of course kinda ugly since we suddenly have to deal with new things...

**Comment by Gnimuc** [comment]
Allowing `-x c++` is not enough for generic C++ support, we need to add C++ standard library and system headers like what has been done in ClangCompiler.jl: https://github.com/Gnimuc/ClangCompiler.jl/blob/master/src/platform/system.jl

**Comment by Gnimuc** [comment]
> Struggles still with:
> 
> ```
> /// Severity of a diagnostic.
> enum MlirDiagnosticSeverity {
>   MlirDiagnosticError,
>   MlirDiagnosticWarning,
>   MlirDiagnosticNote,
>   MlirDiagnosticRemark
> };
> typedef enum MlirDiagnosticSeverity MlirDiagnosticSeverity;
> ```

Is the problem caused by the audit step?

I added an option `no_audit` in [this PR](https://github.com/JuliaInterop/Clang.jl/pull/413/files) which might be helpful...

**Comment by vchuravy** [comment]
> is not enough for generic C++ support, we need to add C++ standard library and system headers like what has been done in ClangCompiler.jl

Yeah I don't need generic C++ support, more C headers written by C++ people... E.g. MLIR headers contain some C++-ism

**Comment by vchuravy** [comment]
> Is this problem caused by the audit step?

No the issue is that C++ mode changes the representation of some of the Clang nodes.
I needed https://github.com/JuliaInterop/Clang.jl/pull/435 to sucesfully parse the MLIR headers.

**Pull request closed without merging**
