### PR TITLE
Move the tests to use ReTest.jl

### PR DESCRIPTION
**Pull request by JamesWrigley**
This allows for a faster workflow when developing the package. Also made a few paths in the tests explicitly relative to the `test/` directory instead of the PWD (since that may not be `test/` when running the tests interactively).

(as discussed on Slack)

### CODE REVIEW

**Comment by JamesWrigley** [comment]
Waiting on https://github.com/JuliaTesting/ReTest.jl/pull/55.

**Comment by Gnimuc** [comment]
Do we need this to be a part of v0.18?

**Comment by JamesWrigley** [comment]
Nah, it's very low-priority.

**Comment by JamesWrigley** [comment]
Ok, this should be ready to go now :) I also saw errors in CI from using the latest BB, so I set compat bounds in 3401cd9.

**Pull request merged**
